# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171104_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='article',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='现在发表'),
        ),
        migrations.AddField(
            model_name='article',
            name='top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='电话'),
        ),
    ]
